### ISSUE TITLE
Resultado Map of Tweets

### ISSUE THREAD

**Issue by csantanaes** [lucasfranklinsilva/Analise-de-Sentimentos#1]
Lucas,
Boa noite. Qual é o resultado do Map of Tweets? 
Fiz conforme está no script mas não plotou dados no mapa.
abraço,

**Comment by lucasfranklinsilva** [comment]
O resultado é um mapa de calor, das regiões com mais tweets relacionados a aquela busca, a causa de não ter aparecido para voce pode ser: 
Alguma dependencia da biblioteca **folium**, se me lembro bem existia alguma coisa que era necessario fazer para que fosse possível gerar o HTML com o mapa.
Outro ponto é que o mapa é gerado via HTML, ele não é visualizado pelo Jupyter, o arquivo fica disponível dentro da pasta.
E por fim, é importante verificar se a busca feita no twitter está retornando a localidade dos mesmos, na versão free da API, só é possível ver a localização de tweets que os usuários tornaram público antes.
